---
- name: install smartd
  apt:
    name:
      - smartmontools
    cache_valid_time: "{{ apt_cache_valid_time }}"
    update_cache: yes
    state: present

- name: config smartd
  copy:
    src: "{{ smartd_conf }}"
    dest: /etc/smartd.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart smartmontools
